"""Admin dashboard — one login, and a read-only window onto the funnels.

Owns: `/admin` (login, overview, funnel detail, A/B panel) and `/admin/api/*`.

Two things this file will not do, and both are load-bearing:

**It never writes.** Every statement it reaches goes through analytics.py, and
every statement in analytics.py is a SELECT. There is no form here that
changes a funnel, no button that refunds a purchase and no endpoint that
takes a POST body of anything but a password. A dashboard that can only look
is a dashboard that can be opened on a phone on a train without care.

**Its pages are not files under static/.** Everything in `static/` is served
by the web server and cached by Cloudflare with no worker in the loop, which
is exactly what makes the funnel fast and exactly what would make an admin
page public. So these pages are rendered here, behind the session check, and
answered `private, no-store`.

The credentials live in `.env` (ADMIN_USER, ADMIN_PASSWORD_HASH) and nowhere
else. Missing, the whole blueprint answers 503 and says so — never an open
dashboard, and never a server that refuses to boot over it.
"""

import base64
import datetime
import functools
import hashlib
import hmac
import ipaddress
import logging
import secrets
import threading
import time

from flask import (Blueprint, jsonify, redirect, render_template, request,
                   session, url_for)

import analytics
import config
import payments

log = logging.getLogger(__name__)

bp = Blueprint("admin", __name__, url_prefix="/admin",
               template_folder="templates/admin")

# The endpoints reachable without a session. Everything else in this blueprint
# — pages and APIs alike — goes through the guard below. Named rather than
# pattern-matched: a new route is private until somebody writes it down here,
# which is the right way round for the default to fail.
PUBLIC_ENDPOINTS = frozenset(("admin.login", "admin.login_post"))

# The one endpoint in this blueprint that writes. Everything else here reads,
# and the suite asserts it statement by statement — so the exception is named
# here rather than left as a thing the tests happen not to catch.
WRITE_ENDPOINTS = frozenset(("admin.modes_post",))


# --- passwords -------------------------------------------------------------

# PBKDF2-HMAC-SHA256, from the standard library.
#
# bcrypt would be the more fashionable answer and it is supported below if the
# stored hash is one — but it is not a dependency here, and the reason is in
# deploy.sh: a deploy deliberately does not run pip, so between shipping a new
# requirement and a human installing it the import is missing. A login that
# cannot be checked because a package has not landed yet is a locked door with
# the key inside. The standard library is always there.
#
# The iteration count is stored in the hash, so raising it later is a new hash
# in .env and nothing else.
PBKDF2_SCHEME = "pbkdf2_sha256"
PBKDF2_ITERATIONS = 240000
BCRYPT_PREFIXES = ("$2a$", "$2b$", "$2y$")


def _b64(raw):
    return base64.b64encode(raw).decode("ascii")


def hash_password(password, iterations=PBKDF2_ITERATIONS, salt=None):
    """`pbkdf2_sha256$<iterations>$<salt>$<hash>` — what goes in .env.

    Generated by `scripts/admin_password.py`; this is the function behind it,
    kept here so the thing that writes a hash and the thing that checks one
    can never be two different implementations.
    """
    if salt is None:
        salt = secrets.token_bytes(16)
    derived = hashlib.pbkdf2_hmac(
        "sha256", password.encode("utf-8"), salt, iterations)
    return "%s$%d$%s$%s" % (PBKDF2_SCHEME, iterations, _b64(salt),
                            _b64(derived))


def _verify_pbkdf2(password, stored):
    try:
        scheme, iterations, salt, derived = stored.split("$")
        iterations = int(iterations)
        salt = base64.b64decode(salt)
        derived = base64.b64decode(derived)
    except (ValueError, TypeError):
        return False
    if scheme != PBKDF2_SCHEME or iterations < 1:
        return False
    candidate = hashlib.pbkdf2_hmac(
        "sha256", password.encode("utf-8"), salt, iterations)
    return hmac.compare_digest(candidate, derived)


def _verify_bcrypt(password, stored):
    """A bcrypt hash, if somebody put one in .env and the module is present.

    Imported inside the function for the same reason the Anthropic SDK is:
    a missing package must degrade to a refused login with a log line, never
    to a site that will not start.
    """
    try:
        import bcrypt
    except ImportError:
        log.error("admin: ADMIN_PASSWORD_HASH is bcrypt but bcrypt is not "
                  "installed; use scripts/admin_password.py for a "
                  "standard-library hash instead")
        return False
    try:
        return bcrypt.checkpw(password.encode("utf-8"),
                              stored.encode("utf-8"))
    except (ValueError, TypeError):
        return False


def verify_password(password, stored):
    """True if `password` is the one `stored` was made from."""
    if not isinstance(password, str) or not isinstance(stored, str):
        return False
    if not stored:
        return False
    if stored.startswith(BCRYPT_PREFIXES):
        return _verify_bcrypt(password, stored)
    return _verify_pbkdf2(password, stored)


def _credentials_set():
    return bool(config.ADMIN_USER) and bool(config.ADMIN_PASSWORD_HASH)


def check_login(username, password):
    """Both halves, with no short circuit between them.

    The password is verified before the username is even looked at, and the
    two answers are combined afterwards. That costs a full PBKDF2 on every
    wrong username, which is the point: a login that returns instantly for an
    unknown user and slowly for a known one has told you the username.
    """
    password_ok = verify_password(password, config.ADMIN_PASSWORD_HASH)
    user_ok = hmac.compare_digest(
        (username or "").encode("utf-8"), config.ADMIN_USER.encode("utf-8"))
    return password_ok and user_ok


# --- session ---------------------------------------------------------------

# What the cookie carries: a stamp over the credentials that were current when
# it was issued. Changing the password in .env changes the stamp, so every
# session opened under the old one stops being valid without anything having
# to be revoked.
SESSION_KEY = "admin_stamp"
CSRF_KEY = "admin_csrf"


def _identity_stamp():
    return hashlib.sha256(
        ("%s\0%s" % (config.ADMIN_USER, config.ADMIN_PASSWORD_HASH))
        .encode("utf-8")).hexdigest()


def _secret_key():
    """What signs the cookie.

    Derived from the password hash when nothing is configured, rather than
    generated per process: this app runs several workers, and a random key
    each would mean a session issued by one worker being rejected by the next.
    """
    if config.ADMIN_SECRET_KEY:
        return config.ADMIN_SECRET_KEY
    return hmac.new(b"mazzin-admin-session",
                    config.ADMIN_PASSWORD_HASH.encode("utf-8"),
                    hashlib.sha256).hexdigest()


def configure(app):
    """Cookie policy and signing key, applied when the blueprint registers.

    At registration rather than per request, and the reason is timing rather
    than taste: Flask opens the session cookie while it is pushing the request
    context, which is before any `before_request` function runs. A key set in
    the guard would arrive one step too late and every session would read as
    empty.

    Registration time is also when the values are final. `config` reads .env
    once at import, so a rotated password or a new ADMIN_SECRET_KEY takes
    effect on the reload that reads it — the same reload every other setting
    in this app needs.

    Public because the suite calls it after moving the credentials, which is
    the one situation where "registration time" happens twice.
    """
    app.config["SECRET_KEY"] = _secret_key()
    app.config["SESSION_COOKIE_NAME"] = "mazzin_admin"
    app.config["SESSION_COOKIE_HTTPONLY"] = True
    app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
    app.config["SESSION_COOKIE_SECURE"] = config.ADMIN_COOKIE_SECURE
    # Scoped to the dashboard. The cookie is then simply not sent on a funnel
    # page load, which is the majority of this server's traffic.
    app.config["SESSION_COOKIE_PATH"] = "/admin"
    app.config["PERMANENT_SESSION_LIFETIME"] = datetime.timedelta(
        seconds=config.ADMIN_SESSION_MAX_AGE_S)


@bp.record_once
def _on_register(state):
    configure(state.app)


def logged_in():
    stamp = session.get(SESSION_KEY)
    if not isinstance(stamp, str) or not stamp:
        return False
    return hmac.compare_digest(stamp, _identity_stamp())


def _start_session():
    """A fresh session on the way in. Never a reused one.

    `session.clear()` first, so the identifier the browser arrives with is not
    the identifier it leaves authenticated with — the CSRF token is reissued
    with it, which is the same fixation problem in a smaller hat.
    """
    session.clear()
    session[SESSION_KEY] = _identity_stamp()
    session[CSRF_KEY] = secrets.token_urlsafe(24)
    session.permanent = True


def csrf_token():
    token = session.get(CSRF_KEY)
    if not isinstance(token, str) or not token:
        token = secrets.token_urlsafe(24)
        session[CSRF_KEY] = token
    return token


def _csrf_ok(form):
    sent = form.get("csrf") or ""
    held = session.get(CSRF_KEY) or ""
    if not held or not sent:
        return False
    return hmac.compare_digest(sent, held)


# --- rate limiting ---------------------------------------------------------

# In memory, per worker, and that is a documented limitation rather than an
# oversight: the alternative is a table, and a login attempt that writes to
# the database is a login attempt an attacker can use to make us write. Several
# workers means the real ceiling is the configured one times the worker count,
# which is still a small number against a PBKDF2 at 240k iterations.
_attempts = {}
_attempts_lock = threading.Lock()

# The bucket every attempt lands in as well as its own. The per-address key is
# read from a header a client can set, so on its own it is a limit somebody can
# step around by rotating it; this one they cannot.
GLOBAL_KEY = "*"


def _client_key():
    """Best-effort client address, parsed before it is believed.

    Cloudflare sits in front of this app, so `remote_addr` is Cloudflare's
    address and the header it sets is the useful one. Every candidate is run
    through `ip_address` first: this value becomes a dictionary key, and an
    unvalidated one would be a string of somebody else's choosing.
    """
    candidates = [request.headers.get("CF-Connecting-IP")]
    forwarded = request.headers.get("X-Forwarded-For") or ""
    if forwarded:
        candidates.append(forwarded.split(",")[0])
    candidates.append(request.remote_addr)
    for value in candidates:
        if not value:
            continue
        try:
            return str(ipaddress.ip_address(value.strip()))
        except ValueError:
            continue
    return "unknown"


# Above this many tracked addresses, the whole table is swept of expired
# entries rather than only the key being asked about. Pruning one bucket per
# request keeps each bucket honest but never removes the key, so a spray of
# addresses against a worker that lives for weeks would grow a dictionary
# nothing ever empties. This is the ceiling on that.
ATTEMPT_KEYS_MAX = 2048


def _prune(bucket, now):
    window = config.ADMIN_LOGIN_WINDOW_S
    return [stamp for stamp in bucket if now - stamp < window]


def _sweep(now):
    """Every key whose attempts have all aged out. Caller holds the lock."""
    if len(_attempts) <= ATTEMPT_KEYS_MAX:
        return
    for key in list(_attempts):
        if key == GLOBAL_KEY:
            continue
        if not _prune(_attempts[key], now):
            del _attempts[key]


def rate_limited(key=None, now=None):
    """True if this client (or everybody together) has spent their attempts."""
    now = now if now is not None else time.time()
    key = key if key is not None else _client_key()
    with _attempts_lock:
        mine = _prune(_attempts.get(key, []), now)
        everyone = _prune(_attempts.get(GLOBAL_KEY, []), now)
        if mine:
            _attempts[key] = mine
        else:
            _attempts.pop(key, None)
        _attempts[GLOBAL_KEY] = everyone
        _sweep(now)
    return (len(mine) >= config.ADMIN_LOGIN_MAX_ATTEMPTS
            or len(everyone) >= config.ADMIN_LOGIN_MAX_ATTEMPTS_GLOBAL)


def record_failure(key=None, now=None):
    now = now if now is not None else time.time()
    key = key if key is not None else _client_key()
    with _attempts_lock:
        for bucket_key in (key, GLOBAL_KEY):
            bucket = _prune(_attempts.get(bucket_key, []), now)
            bucket.append(now)
            _attempts[bucket_key] = bucket
        _sweep(now)


def clear_failures(key=None):
    key = key if key is not None else _client_key()
    with _attempts_lock:
        _attempts.pop(key, None)


def reset_rate_limit():
    """Drop every bucket. For the suite, and for a console locked out."""
    with _attempts_lock:
        _attempts.clear()


# --- the guard -------------------------------------------------------------

def _wants_json():
    return request.path.startswith("/admin/api/")


NOT_CONFIGURED_MESSAGE = (
    "The admin dashboard is not configured. Set ADMIN_USER and "
    "ADMIN_PASSWORD_HASH in .env and reload the app.")


@bp.before_request
def _guard():
    if not _credentials_set():
        # 503 and a sentence, never an open dashboard. This is the shipped
        # state of a fresh deploy and it is not an error worth a traceback.
        if _wants_json():
            return jsonify({"error": "not_configured",
                            "message": NOT_CONFIGURED_MESSAGE}), 503
        return render_template("unconfigured.html",
                               message=NOT_CONFIGURED_MESSAGE), 503

    if request.endpoint in PUBLIC_ENDPOINTS:
        return None

    if not logged_in():
        if _wants_json():
            return jsonify({"error": "unauthenticated"}), 401
        # No `next` on the redirect. There is one page behind this door and
        # the dashboard is it, so a return-to parameter would buy nothing —
        # and a parameter naming where to send somebody after login is how
        # open redirects get written.
        return redirect(url_for("admin.login"))
    return None


@bp.after_request
def _headers(response):
    """Nothing here is cacheable, indexable, or safe to frame."""
    response.headers["Cache-Control"] = "private, no-store"
    response.headers["X-Robots-Tag"] = "noindex, nofollow"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["X-Frame-Options"] = "DENY"
    return response


# --- date ranges -----------------------------------------------------------

RANGE_LABELS = {
    "today": "Today",
    "7d": "Last 7 days",
    "30d": "Last 30 days",
}
DEFAULT_RANGE = "7d"
RANGE_DAYS = {"today": 1, "7d": 7, "30d": 30}


def _parse_date(value):
    try:
        return datetime.datetime.strptime((value or "").strip(),
                                          "%Y-%m-%d")
    except ValueError:
        return None


AUDIENCE_KEY = "audience"
PAID_ONLY = "paid"
ALL_TRAFFIC = "all"
DEFAULT_AUDIENCE = PAID_ONLY


def resolve_audience(args, store=None):
    """Which traffic the page counts: paid only, or everything.

    Paid by default, because that is the question the dashboard exists to
    answer — what the ad spend bought. Direct visits, arrivals from a share
    card and the owner's own test runs are traffic, and none of them are
    performance.

    Sticky per admin session, the same way somebody expects a filter to be:
    set it once and every page keeps it until it is set back. An explicit
    parameter always wins over the stored value, so a pasted URL shows what
    it says rather than what the last click left behind.
    """
    store = session if store is None else store
    asked = (args.get(AUDIENCE_KEY) or "").strip().lower()
    if asked in (PAID_ONLY, ALL_TRAFFIC):
        name = asked
        try:
            store[AUDIENCE_KEY] = name
        except Exception:      # a store that will not take it is not fatal
            pass
    else:
        name = store.get(AUDIENCE_KEY) or DEFAULT_AUDIENCE
        if name not in (PAID_ONLY, ALL_TRAFFIC):
            name = DEFAULT_AUDIENCE
    return {"audience": name, "paid_only": name == PAID_ONLY,
            "label": "Paid only" if name == PAID_ONLY else "All traffic",
            "other": ALL_TRAFFIC if name == PAID_ONLY else PAID_ONLY,
            "other_label": ("All traffic" if name == PAID_ONLY
                            else "Paid only")}


def resolve_range(args, now=None):
    """The window every query on the page runs against.

    Half-open, `[start, end)`, and `end` is the next midnight rather than the
    current moment — so "today" is a stable window that today's events fall
    into as they happen, which is what "computed live" means here. Nothing is
    cached and nothing is precomputed; the day's numbers are whatever the
    table says when the page is asked for.

    A range that will not parse falls back to the default rather than erroring.
    A dashboard is a thing you land on with a URL somebody pasted; it should
    show you something.
    """
    now = now or datetime.datetime.now()
    midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    day = datetime.timedelta(days=1)
    name = (args.get("range") or DEFAULT_RANGE).strip()

    if name == "custom":
        first = _parse_date(args.get("from"))
        last = _parse_date(args.get("to"))
        if first is not None and last is not None and last >= first:
            return {"range": "custom", "start": first, "end": last + day,
                    "from": first.strftime("%Y-%m-%d"),
                    "to": last.strftime("%Y-%m-%d"),
                    "label": "%s to %s" % (first.strftime("%Y-%m-%d"),
                                           last.strftime("%Y-%m-%d"))}
        name = DEFAULT_RANGE

    if name not in RANGE_DAYS:
        name = DEFAULT_RANGE
    start = midnight - datetime.timedelta(days=RANGE_DAYS[name] - 1)
    end = midnight + day
    return {"range": name, "start": start, "end": end,
            "from": start.strftime("%Y-%m-%d"),
            "to": midnight.strftime("%Y-%m-%d"),
            "label": RANGE_LABELS[name]}


def _range_query(window):
    """The range as query-string arguments, for links that keep it."""
    if window["range"] == "custom":
        return {"range": "custom", "from": window["from"], "to": window["to"]}
    return {"range": window["range"]}


def _range_json(window):
    return {"range": window["range"], "label": window["label"],
            "start": window["start"].strftime("%Y-%m-%d %H:%M:%S"),
            "end": window["end"].strftime("%Y-%m-%d %H:%M:%S"),
            "from": window["from"], "to": window["to"]}


# --- assembling the numbers ------------------------------------------------

def _revenue(totals):
    """Per-currency revenue, plus one string for a table cell."""
    rows = [{"currency": t["currency"], "cents": t["cents"],
             "purchases": t["purchases"],
             "display": analytics.format_money(t["cents"], t["currency"])}
            for t in totals if t["cents"] or t["purchases"]]
    rows.sort(key=lambda r: -r["cents"])
    return rows


def _revenue_display(rows):
    return " + ".join(r["display"] for r in rows) if rows else "—"


def overview(window, paid_only=False):
    """One row per funnel. The landing page's whole payload."""
    rows = []
    for slug in analytics.funnel_slugs():
        meta = analytics.funnel_meta(slug)
        counts = analytics.event_counts(slug, window["start"], window["end"],
                                        paid_only=paid_only)
        totals = analytics.purchase_totals(
            slug, window["start"], window["end"], paid_only=paid_only)
        purchases = sum(t["purchases"] for t in totals)
        revenue = _revenue(totals)
        starts = counts["funnel_start"]
        rows.append({
            "slug": slug,
            "title": meta["title"],
            "test_mode": meta["test_mode"],
            "has_variants": bool(meta["variants"]),
            "funnel_start": starts,
            "result_view": counts["result_view"],
            "paywall_view": counts["paywall_view"],
            "pay_tap": counts["pay_tap"],
            "share_tap": counts["share_tap"],
            "purchases": purchases,
            "revenue": revenue,
            "revenue_display": _revenue_display(revenue),
            "conversion": analytics.rate(purchases, starts),
            "result_rate": analytics.rate(counts["result_view"], starts),
            "pay_rate": analytics.rate(counts["pay_tap"],
                                       counts["paywall_view"]),
        })
    totals_row = {
        "funnel_start": sum(r["funnel_start"] for r in rows),
        "result_view": sum(r["result_view"] for r in rows),
        "paywall_view": sum(r["paywall_view"] for r in rows),
        "pay_tap": sum(r["pay_tap"] for r in rows),
        "purchases": sum(r["purchases"] for r in rows),
    }
    by_currency = {}
    for row in rows:
        for cell in row["revenue"]:
            by_currency[cell["currency"]] = (
                by_currency.get(cell["currency"], 0) + cell["cents"])
    totals_row["revenue"] = _revenue(
        [{"currency": code, "cents": cents, "purchases": 0}
         for code, cents in by_currency.items()])
    totals_row["revenue_display"] = _revenue_display(totals_row["revenue"])
    totals_row["conversion"] = analytics.rate(totals_row["purchases"],
                                              totals_row["funnel_start"])
    totals_row["result_rate"] = analytics.rate(totals_row["result_view"],
                                               totals_row["funnel_start"])
    totals_row["pay_rate"] = analytics.rate(totals_row["pay_tap"],
                                            totals_row["paywall_view"])
    return {"funnels": rows, "totals": totals_row}


# How many campaigns get a row of their own before the tail is rolled up. Eight
# is what fits on a phone without a scroll; the rest are summed into `(other)`
# rather than dropped, so the column still adds up to the funnel's total.
TOP_SUBIDS = 8
OTHER_SUBID = "(other)"


def _subid_rows(slug, window, limit=TOP_SUBIDS, paid_only=False):
    events = analytics.subid_events(slug, window["start"], window["end"],
                                    paid_only=paid_only)
    purchases = analytics.subid_purchases(
        slug, window["start"], window["end"], paid_only=paid_only)

    keys = sorted(set(events) | set(purchases),
                  key=lambda k: (-(events.get(k, {}).get("funnel_start", 0)),
                                 k))
    head, tail = keys[:limit], keys[limit:]

    def build(name, members):
        counts = {event: 0 for event in analytics.FUNNEL_EVENTS}
        for member in members:
            for event, value in (events.get(member) or {}).items():
                counts[event] = counts.get(event, 0) + value
        by_currency = {}
        sales = 0
        for member in members:
            for cell in (purchases.get(member) or []):
                by_currency[cell["currency"]] = (
                    by_currency.get(cell["currency"], 0) + cell["cents"])
                sales += cell["purchases"]
        revenue = _revenue([{"currency": code, "cents": cents,
                             "purchases": 0}
                            for code, cents in by_currency.items()])
        return {"subid": name, "purchases": sales, "revenue": revenue,
                "revenue_display": _revenue_display(revenue),
                "conversion": analytics.rate(sales, counts["funnel_start"]),
                **counts}

    rows = [build(key, [key]) for key in head]
    if tail:
        rows.append(build(OTHER_SUBID, tail))
    return rows


def _unattributed(totals, subid_rows):
    """Sales in the window whose `funnel_start` is not.

    The per-subid table joins a purchase to the campaign its session arrived
    on; a reader who started yesterday and paid today has no start row inside
    the window, so the join drops them. Dropping them silently would make the
    subid column stop adding up to the funnel's own total, which is the kind
    of quiet disagreement that makes a dashboard stop being believed. So the
    difference is computed and shown.

    Takes the funnel's totals rather than fetching them: the caller already
    has them, and `purchases` has no index on (funnel, created_at) — every
    read of it is a table scan, so the dashboard does not do it twice.
    """
    by_currency = {t["currency"]: t["cents"] for t in totals}
    sales = sum(t["purchases"] for t in totals)
    for row in subid_rows:
        sales -= row["purchases"]
        for cell in row["revenue"]:
            by_currency[cell["currency"]] = (
                by_currency.get(cell["currency"], 0) - cell["cents"])
    revenue = _revenue([{"currency": code, "cents": cents, "purchases": 0}
                        for code, cents in by_currency.items() if cents > 0])
    if sales <= 0 and not revenue:
        return None
    return {"subid": analytics.UNATTRIBUTED,
            "purchases": max(sales, 0),
            "revenue": revenue,
            "revenue_display": _revenue_display(revenue),
            "conversion": 0.0,
            **{event: 0 for event in analytics.FUNNEL_EVENTS}}


def ad_url(slug):
    """The funnel's canonical public URL — what goes in an ad's final URL.

    Built from BASE_URL rather than written out, so a staging deploy shows its
    own hostname instead of handing somebody production's by mistake.
    """
    return "%s/%s" % (config.BASE_URL.rstrip("/"), slug)


def step_breakdown(slug, window, paid_only=False):
    """Per step, which option readers actually tapped.

    Readable with no change to the write path, because tracking.py already
    stores the answer: every swipe carries the pair that was drawn and the
    image that was chosen, both validated against the funnel's own config when
    they were written. So this is the config's labels joined onto a group-by.

    One block per pair, not one per step. A step with two pairs draws one of
    them per session, so a reader who saw the wood pair could not have picked
    a stone; a single percentage across both would divide by a denominator
    nobody was ever shown.

    Zero-filled from the config, because an option nobody picks is the most
    interesting row here and a GROUP BY cannot return it.
    """
    picked = analytics.step_selections(
        slug, window["start"], window["end"], paid_only=paid_only)
    seen_keys = set()
    steps = []

    for step in analytics.funnel_steps(slug):
        blocks = []
        for pair in step["pairs"]:
            key = (step["step"], pair["key"])
            seen_keys.add(key)
            counts = picked.get(key, {})
            total = sum(counts.values())
            declared = {image["id"] for image in pair["images"]}
            options = [{
                "id": image["id"],
                "label": image["label"],
                "img": image["img"],
                "sessions": counts.get(image["id"], 0),
                "share": analytics.rate(counts.get(image["id"], 0), total),
                "retired": False,
            } for image in pair["images"]]
            # An id in the data that the config no longer declares: a gallery
            # edited under a live funnel. Its taps happened and are shown,
            # marked, rather than quietly dropped out of the denominator.
            for orphan in sorted(set(counts) - declared):
                options.append({
                    "id": orphan, "label": orphan, "img": None,
                    "sessions": counts[orphan],
                    "share": analytics.rate(counts[orphan], total),
                    "retired": True,
                })
            options.sort(key=lambda option: (-option["sessions"],
                                             option["label"]))
            blocks.append({"key": pair["key"], "id": pair["id"],
                           "total": total, "options": options})
        steps.append({
            "step": step["step"],
            "id": step["id"],
            "question": step["question"],
            "format": step["format"],
            "multi": len(blocks) > 1,
            "total": sum(block["total"] for block in blocks),
            "blocks": blocks,
        })

    # Rows whose pair the config does not describe at all — a step renamed, or
    # a pair retired outright. Grouped under the step they were recorded on so
    # the numbers still add up to what the table holds.
    by_step = {step["step"]: step for step in steps}
    for (number, pair_key), counts in sorted(picked.items()):
        if (number, pair_key) in seen_keys:
            continue
        total = sum(counts.values())
        options = sorted(
            ({"id": image, "label": image, "img": None, "sessions": count,
              "share": analytics.rate(count, total), "retired": True}
             for image, count in counts.items()),
            key=lambda option: (-option["sessions"], option["label"]))
        block = {"key": pair_key, "id": pair_key, "total": total,
                 "options": options, "retired": True}
        step = by_step.get(number)
        if step is None:
            continue
        step["blocks"].append(block)
        step["multi"] = len(step["blocks"]) > 1
        step["total"] += total

    return steps


def funnel_detail(slug, window, paid_only=False):
    """Everything the detail page draws, and the JSON behind it."""
    meta = analytics.funnel_meta(slug)
    counts = analytics.event_counts(slug, window["start"], window["end"],
                                    paid_only=paid_only)
    totals = analytics.purchase_totals(slug, window["start"], window["end"],
                                       paid_only=paid_only)
    purchases = sum(t["purchases"] for t in totals)
    revenue = _revenue(totals)

    seen = analytics.swipe_steps(slug, window["start"], window["end"],
                                 paid_only=paid_only)
    # Every step the config declares, whether or not anybody reached it. A
    # missing row is the most interesting row on a drop-off chart and it must
    # not be the one the query leaves out.
    top = max([seen.get(n, 0) for n in range(1, meta["steps"] + 1)] or [0])
    steps = []
    for number in range(1, meta["steps"] + 1):
        reached = seen.get(number, 0)
        steps.append({
            "step": number,
            "sessions": reached,
            "of_start": analytics.rate(reached, counts["funnel_start"]),
            "of_first": analytics.rate(reached, top),
        })

    rows = _subid_rows(slug, window, paid_only=paid_only)
    leftover = _unattributed(totals, rows)
    if leftover:
        rows.append(leftover)

    detail = {
        "funnel": {"slug": slug, "title": meta["title"],
                   "funnel_id": meta["funnel_id"], "steps": meta["steps"],
                   "test_mode": meta["test_mode"],
                   "shares": meta["shares"]},
        "events": counts,
        "purchases": purchases,
        "revenue": revenue,
        "revenue_display": _revenue_display(revenue),
        "conversion": analytics.rate(purchases, counts["funnel_start"]),
        "result_rate": analytics.rate(counts["result_view"],
                                      counts["funnel_start"]),
        "pay_rate": analytics.rate(counts["pay_tap"], counts["paywall_view"]),
        "steps": steps,
        "selections": step_breakdown(slug, window, paid_only=paid_only),
        "ad_url": ad_url(slug),
        "subids": rows,
        "share_tap": counts["share_tap"] if meta["shares"] else None,
        "variants": (variants(slug, window, meta=meta, paid_only=paid_only)
                     if meta["variants"] else None),
    }
    return detail


def variants(slug, window, meta=None, paid_only=False):
    """The A/B panel: what the config says is live, and what it did.

    Both halves matter and neither answers the other's question. The config
    half says which arms are switched on and at what share, read the same way
    result_persona.js reads it; the measured half is the shared query the
    console script prints. An arm disabled this morning still has yesterday's
    numbers, and it is shown with them and marked off — which is the only
    honest way to read a test somebody has already stopped.
    """
    meta = meta or analytics.funnel_meta(slug)
    rows = analytics.variant_rows(slug, window["start"], window["end"],
                                  paid_only=paid_only)
    declared = {arm["id"]: arm for arm in meta["variants"]}

    def cell(row):
        shown = int(row["shown"] or 0)
        reached = int(row["reached"] or 0)
        paid = int(row["paid"] or 0)
        return {"variant": row["variant"], "subid": row["subid"],
                "shown": shown, "reached": reached, "paid": paid,
                "rate": analytics.rate(paid, shown),
                "reach_rate": analytics.rate(reached, shown)}

    overall = [cell(row) for row in analytics.fold_variants(rows)]
    measured = {row["variant"] for row in rows}
    for arm_id, arm in declared.items():
        if arm_id not in measured:
            overall.append({"variant": arm_id, "subid": "(all)", "shown": 0,
                            "reached": 0, "paid": 0, "rate": 0.0,
                            "reach_rate": 0.0})
    for row in overall:
        arm = declared.get(row["variant"])
        row["name"] = arm["name"] if arm else row["variant"]
        row["enabled"] = arm["enabled"] if arm else False
        row["weight"] = arm["weight"] if arm else 0
        row["share"] = arm["share"] if arm else 0.0
        # An arm with rows in the table and no entry in the config is one
        # that was deleted rather than disabled. Its history is real and is
        # shown; the flag is what says not to expect more of it.
        row["declared"] = arm is not None
    overall.sort(key=lambda r: (not r["enabled"], -r["shown"], r["variant"]))

    return {"funnel": slug, "declared": meta["variants"],
            "overall": overall,
            "by_subid": sorted((cell(row) for row in rows),
                               key=lambda r: (r["variant"], -r["shown"]))}


# --- routes ----------------------------------------------------------------

def _json_error(exc, what):
    log.exception("admin: %s failed", what)
    return jsonify({"error": "query_failed",
                    "message": "The database did not answer. %s" % what}), 503


def _guarded(what):
    """Wrap a route so a database that is down is a sentence, not a stack.

    This dashboard reads a database over a network from a page somebody opens
    on a phone. When that fails the useful answer is "the database did not
    answer", not a 500 whose body is an HTML error page the JSON caller cannot
    parse.
    """
    def wrap(view):
        @functools.wraps(view)
        def inner(*args, **kwargs):
            try:
                return view(*args, **kwargs)
            except Exception as exc:      # noqa: BLE001 - reported, not hidden
                if _wants_json():
                    return _json_error(exc, what)
                log.exception("admin: %s failed", what)
                return render_template("unconfigured.html",
                                       message="The database did not answer. "
                                               "Try again in a moment."), 503
        return inner
    return wrap


@bp.get("/login")
def login():
    if logged_in():
        return redirect(url_for("admin.index"))
    return render_template("login.html", csrf=csrf_token(), error=None), 200


@bp.post("/login")
def login_post():
    form = request.form
    if rate_limited():
        log.warning("admin: login refused, rate limit")
        return render_template(
            "login.html", csrf=csrf_token(),
            error="Too many attempts. Try again later."), 429

    if not _csrf_ok(form):
        # Not counted as a failed password: a missing token is usually a stale
        # tab or a browser that dropped the cookie, and burning the attempt
        # budget on it would lock the owner out of their own dashboard.
        return render_template(
            "login.html", csrf=csrf_token(),
            error="That form expired. Try again."), 400

    if not check_login(form.get("username"), form.get("password")):
        record_failure()
        # No username, no address, nothing about the attempt. The house rule
        # about logs does not have an exception for the login page.
        log.warning("admin: login failed")
        return render_template(
            "login.html", csrf=csrf_token(),
            error="Wrong username or password."), 401

    clear_failures()
    _start_session()
    return redirect(url_for("admin.index"))


@bp.post("/logout")
def logout():
    if not _csrf_ok(request.form):
        # Refused out loud rather than redirected. A logout that quietly does
        # not log you out, on a page that then looks logged out, is how
        # somebody walks away from a borrowed phone believing they left.
        return render_template(
            "unconfigured.html",
            message="That form expired — go back and try again."), 400
    session.clear()
    return redirect(url_for("admin.login"))


@bp.get("/")
@bp.get("")
@_guarded("the overview")
def index():
    window = resolve_range(request.args)
    audience = resolve_audience(request.args)
    data = overview(window, paid_only=audience["paid_only"])
    return render_template("overview.html", window=window, audience=audience,
                           range_query=_range_query(window),
                           csrf=csrf_token(), **data)


@bp.get("/funnel/<slug>")
@_guarded("the funnel detail")
def funnel(slug):
    if slug not in analytics.funnel_slugs():
        return render_template("unconfigured.html",
                               message="No funnel called %r." % slug), 404
    window = resolve_range(request.args)
    audience = resolve_audience(request.args)
    detail = funnel_detail(slug, window, paid_only=audience["paid_only"])
    return render_template("funnel.html", window=window, audience=audience,
                           range_query=_range_query(window),
                           # The switcher down the left. Every funnel, so the
                           # page is a place to move between them rather than
                           # somewhere you arrive from the overview and go back.
                           siblings=[analytics.funnel_meta(other)
                                     for other in analytics.funnel_slugs()],
                           csrf=csrf_token(), **detail)


# --- JSON ------------------------------------------------------------------
# Everything the pages draw is also here, under /admin/api/*, because the next
# feature is going to want it. Same functions, same window parsing, same
# session check — the pages are one renderer of these payloads and not a
# second source of them.

@bp.get("/api/funnels")
@_guarded("the funnel list")
def api_funnels():
    return jsonify({"funnels": [analytics.funnel_meta(slug)
                                for slug in analytics.funnel_slugs()]})


@bp.get("/api/overview")
@_guarded("the overview")
def api_overview():
    window = resolve_range(request.args)
    audience = resolve_audience(request.args)
    payload = overview(window, paid_only=audience["paid_only"])
    payload["range"] = _range_json(window)
    payload["audience"] = audience["audience"]
    payload["counted"] = "unique sessions"
    return jsonify(payload)


@bp.get("/api/funnel/<slug>")
@_guarded("the funnel detail")
def api_funnel(slug):
    if slug not in analytics.funnel_slugs():
        return jsonify({"error": "unknown_funnel"}), 404
    window = resolve_range(request.args)
    audience = resolve_audience(request.args)
    payload = funnel_detail(slug, window, paid_only=audience["paid_only"])
    payload["range"] = _range_json(window)
    payload["audience"] = audience["audience"]
    payload["counted"] = "unique sessions"
    return jsonify(payload)


@bp.get("/api/variants/<slug>")
@_guarded("the variant stats")
def api_variants(slug):
    if slug not in analytics.funnel_slugs():
        return jsonify({"error": "unknown_funnel"}), 404
    window = resolve_range(request.args)
    audience = resolve_audience(request.args)
    payload = variants(slug, window, paid_only=audience["paid_only"])
    payload["range"] = _range_json(window)
    payload["audience"] = audience["audience"]
    return jsonify(payload)


# --- the Stripe mode switch ------------------------------------------------
#
# The one page in this blueprint that writes, and what it writes is the most
# consequential switch on the site: a funnel in test mode takes no money from
# anybody. So everything here is built around making the current state
# impossible to misread and the dangerous state impossible to sit in unnoticed.
#
# It is behind the dashboard's own session, like every other page here. There
# is no second credential and no second door: one admin login, one place to be
# logged in, and one set of rate-limited attempts guarding it.

# How far back the page looks for traffic when deciding whether a funnel in
# test mode is a live problem. A day covers an overnight ad run, which is
# exactly the case this banner exists for.
LIVE_TRAFFIC_WINDOW = datetime.timedelta(hours=24)

# `changed_by` is the admin who was logged in, truncated to the column. It goes
# in the row and deliberately not in the log line: a row in a table somebody
# has to query is a record, and a username in an application log is the thing
# the no-PII rule is about.
CHANGED_BY_MAX = 64


def _changed_by():
    return (config.ADMIN_USER or "admin")[:CHANGED_BY_MAX]

# The keys a mode needs before a funnel may be put into it. All three, because
# two out of three is the half-configured state this refuses to create: a
# secret with no webhook secret takes money and never records the purchase, and
# a secret with no publishable key cannot confirm a payment in the page.
MODE_KEYS = {
    "live": (("STRIPE_SECRET_KEY", "STRIPE_SECRET_KEY"),
             ("STRIPE_WEBHOOK_SECRET", "STRIPE_WEBHOOK_SECRET"),
             ("STRIPE_PUBLISHABLE_KEY", "STRIPE_PUBLISHABLE_KEY")),
    "test": (("STRIPE_TEST_SECRET_KEY", "STRIPE_TEST_SECRET_KEY"),
             ("STRIPE_TEST_WEBHOOK_SECRET", "STRIPE_TEST_WEBHOOK_SECRET"),
             ("STRIPE_TEST_PUBLISHABLE_KEY", "STRIPE_TEST_PUBLISHABLE_KEY")),
}

MESSAGES = {
    "ok": "%s is now in %s mode.",
    "cleared": "%s is back on whatever its config says.",
    "keys": "%s was not switched: %s mode is missing %s in .env. "
            "A funnel half-switched into a mode it has no keys for cannot "
            "take a payment at all.",
    "table": "Nothing was saved: the funnel_mode_overrides table is not there "
             "yet. Apply the migration in schema_migrations.sql on the "
             "server, then try again.",
    "bad": "That request did not name a funnel and a mode this page knows.",
}


def _missing_keys(mode):
    """Which of a mode's three keys are not set. Empty when it is ready."""
    return [name for name, attr in MODE_KEYS[mode]
            if not getattr(config, attr, "")]


def _recent_starts(slug, now):
    """Sessions that began this funnel in the last day. 0 if unknowable.

    A database that will not answer must not turn the warning banner into a
    stack trace — the page's job in that moment is still to show which funnel
    is in which mode.
    """
    try:
        counts = analytics.event_counts(
            slug, now - LIVE_TRAFFIC_WINDOW, now, events=("funnel_start",))
    except Exception:                  # noqa: BLE001 - the page still renders
        log.exception("admin: recent traffic lookup failed for %s", slug)
        return 0
    return counts.get("funnel_start", 0)


def _mode_rows(now):
    """One row per funnel: what the config says, what it is actually doing."""
    overrides = payments.all_overrides()
    rows = []
    for slug in analytics.funnel_slugs():
        meta = analytics.funnel_meta(slug)
        override = overrides.get(slug)
        config_mode = payments.TEST if meta["test_mode"] else payments.LIVE
        effective = (override or {}).get("mode") or config_mode
        starts = _recent_starts(slug, now)
        rows.append({
            "slug": slug,
            "title": meta["title"],
            "config_mode": config_mode,
            "effective": effective,
            "overridden": override is not None,
            "changed_at": (override or {}).get("changed_at"),
            "changed_by": (override or {}).get("changed_by"),
            "recent_starts": starts,
            # The state this page exists to make impossible to miss: readers
            # are arriving and none of them can pay.
            "danger": effective == payments.TEST and starts > 0,
        })
    return rows


def _modes_page(status=200, message=None, level="info"):
    now = datetime.datetime.now()
    rows = _mode_rows(now)
    return render_template(
        "modes.html",
        rows=rows,
        csrf=csrf_token(),
        message=message,
        level=level,
        alarms=[row for row in rows if row["danger"]],
        now=now.strftime("%Y-%m-%d %H:%M"),
    ), status


@bp.get("/modes")
def modes():
    code = request.args.get("msg") or ""
    funnel = request.args.get("f") or ""
    message, level = None, "info"
    if code == "ok":
        message = MESSAGES["ok"] % (funnel, request.args.get("m") or "")
        level = "good"
    elif code == "cleared":
        message = MESSAGES["cleared"] % funnel
        level = "good"
    elif code == "keys":
        message = MESSAGES["keys"] % (funnel, request.args.get("m") or "",
                                      request.args.get("k") or "a key")
        level = "bad"
    elif code in ("table", "bad"):
        message = MESSAGES[code]
        level = "bad"
    return _modes_page(message=message, level=level)


@bp.post("/modes")
def modes_post():
    # The session cookie alone is not authority to flip a funnel into test
    # mode: a cross-site form would send it for free. The dashboard already
    # issues a token for exactly this and both other forms here carry it.
    if not _csrf_ok(request.form):
        return render_template(
            "unconfigured.html",
            message="That form expired — reload the page and try again."), 400

    slug = request.form.get("funnel") or ""
    action = request.form.get("action") or ""
    mode = request.form.get("mode") or ""

    if slug not in analytics.funnel_slugs():
        return redirect(url_for("admin.modes", msg="bad"))

    before = payments.effective_mode(slug)

    if action == "clear":
        try:
            payments.clear_override(slug)
        except Exception:                         # noqa: BLE001 - reported
            log.exception("admin: clearing the mode override for %s failed",
                          slug)
            return redirect(url_for("admin.modes", msg="table"))
        after = payments.effective_mode(slug)
        _log_switch(slug, before, after, "cleared")
        return redirect(url_for("admin.modes", msg="cleared", f=slug))

    if action != "set" or mode not in (payments.LIVE, payments.TEST):
        return redirect(url_for("admin.modes", msg="bad"))

    # Never a silent half-switched state. A funnel put into a mode whose keys
    # are not in .env refuses every checkout with a 502 — which reads, from
    # outside, exactly like the site being broken.
    missing = _missing_keys(mode)
    if missing:
        log.warning("admin: refused to put %s into %s mode — missing %s",
                    slug, mode, ", ".join(missing))
        return redirect(url_for("admin.modes", msg="keys", f=slug, m=mode,
                                k=", ".join(missing)))

    try:
        payments.set_override(slug, mode, _changed_by())
    except Exception:                             # noqa: BLE001 - reported
        log.exception("admin: writing the mode override for %s failed", slug)
        return redirect(url_for("admin.modes", msg="table"))

    _log_switch(slug, before, mode, "set")
    return redirect(url_for("admin.modes", msg="ok", f=slug, m=mode))


def _log_switch(slug, before, after, how):
    """One line per switch: the funnel, the transition, the time.

    Not the username. That is on the row, where somebody investigating goes
    looking for it; the application log is read by more things and by more
    people, and the house rule about what goes in it has no exception for
    this page.
    """
    log.warning("stripe mode %s: funnel=%s %s->%s at=%s",
                how, slug, before, after,
                datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S"))
